### ISSUE TITLE
re: career opportunities (associate to junior level) in Deutschland

### ISSUE THREAD

**Issue by juwalter** [arhat-dev/aranya#6]
Hello Jeff, I could not track your contact details down (jeff.arhat.dev seems down) - we are currently looking to deploy a device management solution for out IIoT device - your design looks very promising and I would like to explore! Other than that, we are heavy users of K8s, Linux, C++ and Scala. Pls do get in touch jw at datatroniq dot com. Cheers, Jürgen

**Comment by jeffreystoke** [comment]
Hi @juwalter, I've just sent an email to you, I'm closing this issue since it will be talked in private channels.

Please feel free to reopen it if you encountered any related problem.
